# Generated by rust2rpm 23
%bcond_without check
%global debug_package %{nil}

%global crate ticky

Name:           rust-ticky
Version:        0.1.0
Release:        %autorelease
Summary:        Stopwatch library, written in Rust

License:        AGPL-3.0-or-later
URL:            https://crates.io/crates/ticky
Source:         %{crates_source}

BuildRequires:  rust-packaging >= 21

%global _description %{expand:
Stopwatch library, written in Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/LICENSE.md
%license %{crate_instdir}/NOTICE
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README
%doc %{crate_instdir}/SECURITY.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive_more-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive_more-devel %{_description}

This package contains library source intended for building other packages which
use the "derive_more" feature of the "%{crate}" crate.

%files       -n %{name}+derive_more-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
