# Generated by rust2rpm 24
%bcond_without check

%global crate ticky

Name:           rust-ticky
Version:        1.0.2
Release:        %autorelease
Summary:        Stopwatch library, written in Rust

License:        AGPL-3.0-or-later
URL:            https://crates.io/crates/ticky
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A stopwatch library, written in Rust.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license COPYING
%license LICENSE.md
%license NOTICE
%license LICENSE.dependencies
%doc CODE_OF_CONDUCT.md
%doc CONTRIBUTING.md
%doc README
%doc SECURITY.md

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/COPYING
%license %{crate_instdir}/LICENSE.md
%license %{crate_instdir}/NOTICE
%doc %{crate_instdir}/CODE_OF_CONDUCT.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/README
%doc %{crate_instdir}/SECURITY.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive_more-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive_more-devel %{_description}

This package contains library source intended for building other packages which
use the "derive_more" feature of the "%{crate}" crate.

%files       -n %{name}+derive_more-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hifitime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hifitime-devel %{_description}

This package contains library source intended for building other packages which
use the "hifitime" feature of the "%{crate}" crate.

%files       -n %{name}+hifitime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stdtime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stdtime-devel %{_description}

This package contains library source intended for building other packages which
use the "stdtime" feature of the "%{crate}" crate.

%files       -n %{name}+stdtime-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install
# FIXME: install shared library

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
