on:
  push:
    branches:    
      - 'master'

name: 'Package: RPM for GNU + Linux (x86_64)'

jobs:
  rpm_x86-64:
    name: Fedora GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      volumes:
        - /proc:/proc
        - /sys/fs/cgroup/systemd/actions_job:/sys/fs/cgroup/systemd/actions_job
        - /sys/fs/cgroup:/sys/fs/cgroup
      options: --privileged
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install compiler toolchain
        run: |
          sudo dnf -q -y install gcc rpm-build rpmdevtools rpmlint python3-rust2rpm rust-packaging packit tree perl perl-FindBin perl-lib > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Generate RPM package specification
        run: |
          rpmdev-setuptree
          rust2rpm .
          cp ./rust-ticky.spec ~/rpmbuild/SPECS/
          rpmlint ~/rpmbuild/SPECS/rust-ticky.spec
      - name: Build & package Ticky
        run: |
          cargo package --all-features
          mv ./target/package/ticky-*.crate ~/rpmbuild/SOURCES/
          cd ~/rpmbuild/SOURCES/
          spectool -g -R ~/rpmbuild/SPECS/rust-ticky.spec
          cd -
          tree ~/rpmbuild/
          tree ./
          packit srpm ./
          packit build locally ./
          tree ./
      - name: Commit changes to RPM package specification file, if any
        run: |
          git config --global user.name 'Ticky'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatically updated RPM package specification"
          git push
      - name: Upload Ticky package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-ticky.rpm.gnu+linux
          path: "*.rpm"
          if-no-files-found: error
      - name: Upload Ticky source package to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-ticky.rpm.gnu+linux
          path: "*.src.rpm"
          if-no-files-found: error