on:
  push:
    branches:    
      - 'master'

name: 'Build: Windows (x86_64)'

jobs:
  windows_x86-64:
    name: Windows (x86_64)
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "MINGW64: Install, setup, and switch to"
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-pkg-config
      - name: Setup environment variables
        run: |
          echo "../../_temp/msys/msys64/mingw64/bin" >> $GITHUB_PATH
          LIBRARY_PATH="../../_temp/msys/msys64/mingw64/bin"
          PKG_CONFIG="../../_temp/msys/msys64/mingw64/bin" PKG_CONFIG_ALLOW_CROSS=1
          source ~/.bashrc
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-gnu
          target: x86_64-pc-windows-gnu
          default: true
          profile: minimal
      - name: Build Ticky
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu
      - name: Prepare Ticky for upload
        run: |
          cd ./target/x86_64-pc-windows-gnu/release/
          tar -czvf x86_64-ticky.win32.zip \
          ticky.dll \
          libticky.a \
          libticky.dll.a
      - name: Upload Ticky build artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-ticky.win32
          path: ./target/x86_64-pc-windows-gnu/release/x86_64-ticky.win32.zip
          if-no-files-found: error