on:
  push:
    branches:    
      - 'master'

name: 'Build: GNU + Linux (x86_64)'

jobs:
  linux_x86-64:
    name: GNU + Linux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq build-essential > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Build Ticky
        uses: actions-rs/cargo@v1
        with:
          use-cross: false
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Prepare Ticky for upload
        run: |
          cd ./target/x86_64-unknown-linux-gnu/release/
          tar -cvf x86_64-ticky.gnu+linux.tar \
          libticky.so \
          libticky.a
      - name: Upload Ticky build artifacts to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-ticky.gnu+linux
          path: ./target/x86_64-unknown-linux-gnu/release/x86_64-ticky.gnu+linux.tar
          if-no-files-found: error